apiVersion: v1
kind: Pod
metadata:
  name: volume-pod
spec:
  containers:
    - name: nginx-container
      image: nginx
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: windows-volume
  volumes:
    - name: windows-volume
      hostPath:
        path: /run/desktop/mnt/host/c/k8s-data 
        type: Directory
